[2024-06-08 23:20:36,432] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
W0608 23:20:36.880000 140396167001088 torch/distributed/run.py:757] 
W0608 23:20:36.880000 140396167001088 torch/distributed/run.py:757] *****************************************
W0608 23:20:36.880000 140396167001088 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0608 23:20:36.880000 140396167001088 torch/distributed/run.py:757] *****************************************
[2024-06-08 23:20:38,989] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-06-08 23:20:38,989] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-devel package with yum
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
[93m [WARNING] [0m async_io: please install the libaio-devel package with yum
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
[93m [WARNING] [0m sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
[93m [WARNING] [0m using untested triton version (2.3.1), only 1.0.0 is known to be compatible
[93m [WARNING] [0m sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
[93m [WARNING] [0m using untested triton version (2.3.1), only 1.0.0 is known to be compatible
[2024-06-08 23:20:39,152] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-06-08 23:20:39,152] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2024-06-08 23:20:39,160] [INFO] [comm.py:637:init_distributed] cdb=None
2024-06-08 23:20:39 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1 distributed training: True, 16-bits training: False
2024-06-08 23:20:39 - INFO - __main__ - Training/evaluation parameters TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
batch_eval_metrics=False,
bf16=True,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
dispatch_batches=None,
do_eval=False,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_steps=None,
eval_strategy=no,
evaluation_strategy=None,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=True,
gradient_checkpointing_kwargs={'use_reentrant': False},
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
include_num_input_tokens_seen=False,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-06,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=info,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=./checkpoint_dir/runs/Jun08_23-20-39_JF5300-B11A265T,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=20,
logging_strategy=steps,
lr_scheduler_kwargs={},
lr_scheduler_type=cosine,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=1,
optim=adamw_torch,
optim_args=None,
optim_target_modules=None,
output_dir=./checkpoint_dir,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=4,
per_device_train_batch_size=4,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=./checkpoint_dir,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=100,
save_strategy=steps,
save_total_limit=1,
seed=0,
skip_memory_metrics=True,
split_batches=None,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.2,
warmup_steps=0,
weight_decay=0.0,
)
2024-06-08 23:20:39 - INFO - __main__ - PEFT parameters LoraConfig(peft_type=<PeftType.LORA: 'LORA'>, auto_mapping=None, base_model_name_or_path=None, revision=None, task_type='CAUSAL_LM', inference_mode=False, r=16, target_modules='all-linear', lora_alpha=32, lora_dropout=0.05, fan_in_fan_out=False, bias='none', use_rslora=False, modules_to_save=None, init_lora_weights=True, layers_to_transform=None, layers_pattern=None, rank_pattern={}, alpha_pattern={}, megatron_config=None, megatron_core='megatron.core', loftq_config={}, use_dora=False, layer_replication=None)
2024-06-08 23:20:39 - WARNING - __main__ - Process rank: 1, device: cuda:1, n_gpu: 1 distributed training: True, 16-bits training: False
[INFO|configuration_utils.py:733] 2024-06-08 23:20:39,338 >> loading configuration file config.json from cache at /nvm/.cache/huggingface/hub/models--microsoft--Phi-3-mini-4k-instruct/snapshots/d269012bea6fbe38ce7752c8940fea010eea3383/config.json
[INFO|configuration_utils.py:733] 2024-06-08 23:20:39,432 >> loading configuration file config.json from cache at /nvm/.cache/huggingface/hub/models--microsoft--Phi-3-mini-4k-instruct/snapshots/d269012bea6fbe38ce7752c8940fea010eea3383/config.json
[INFO|configuration_utils.py:796] 2024-06-08 23:20:39,433 >> Model config Phi3Config {
  "_name_or_path": "microsoft/Phi-3-mini-4k-instruct",
  "architectures": [
    "Phi3ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "auto_map": {
    "AutoConfig": "microsoft/Phi-3-mini-4k-instruct--configuration_phi3.Phi3Config",
    "AutoModelForCausalLM": "microsoft/Phi-3-mini-4k-instruct--modeling_phi3.Phi3ForCausalLM"
  },
  "bos_token_id": 1,
  "embd_pdrop": 0.0,
  "eos_token_id": 32000,
  "hidden_act": "silu",
  "hidden_size": 3072,
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "max_position_embeddings": 4096,
  "model_type": "phi3",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "original_max_position_embeddings": 4096,
  "pad_token_id": 32000,
  "resid_pdrop": 0.0,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "sliding_window": 2047,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.41.2",
  "use_cache": false,
  "vocab_size": 32064
}

2024-06-08 23:20:39 - WARNING - transformers_modules.microsoft.Phi-3-mini-4k-instruct.d269012bea6fbe38ce7752c8940fea010eea3383.modeling_phi3 - `flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
2024-06-08 23:20:39 - WARNING - transformers_modules.microsoft.Phi-3-mini-4k-instruct.d269012bea6fbe38ce7752c8940fea010eea3383.modeling_phi3 - Current `flash-attention` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.
[INFO|modeling_utils.py:3474] 2024-06-08 23:20:39,615 >> loading weights file model.safetensors from cache at /nvm/.cache/huggingface/hub/models--microsoft--Phi-3-mini-4k-instruct/snapshots/d269012bea6fbe38ce7752c8940fea010eea3383/model.safetensors.index.json
[INFO|modeling_utils.py:1519] 2024-06-08 23:20:39,616 >> Instantiating Phi3ForCausalLM model under default dtype torch.bfloat16.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/nvm/phi3finetune/finetune.py", line 138, in <module>
[rank0]:     model = AutoModelForCausalLM.from_pretrained(checkpoint_path, **model_kwargs)
[rank0]:   File "/root/.conda/envs/llm/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
[rank0]:     return model_class.from_pretrained(
[rank0]:   File "/root/.conda/envs/llm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3620, in from_pretrained
[rank0]:     config = cls._autoset_attn_implementation(
[rank0]:   File "/root/.conda/envs/llm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1469, in _autoset_attn_implementation
[rank0]:     cls._check_and_enable_flash_attn_2(
[rank0]:   File "/root/.conda/envs/llm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1571, in _check_and_enable_flash_attn_2
[rank0]:     raise ImportError(f"{preface} the package flash_attn seems to be not installed. {install_message}")
[rank0]: ImportError: FlashAttention2 has been toggled on, but it cannot be used due to the following error: the package flash_attn seems to be not installed. Please refer to the documentation of https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2 to install Flash Attention 2.
2024-06-08 23:20:39 - WARNING - transformers_modules.microsoft.Phi-3-mini-4k-instruct.d269012bea6fbe38ce7752c8940fea010eea3383.modeling_phi3 - `flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
2024-06-08 23:20:39 - WARNING - transformers_modules.microsoft.Phi-3-mini-4k-instruct.d269012bea6fbe38ce7752c8940fea010eea3383.modeling_phi3 - Current `flash-attention` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/nvm/phi3finetune/finetune.py", line 138, in <module>
[rank1]:     model = AutoModelForCausalLM.from_pretrained(checkpoint_path, **model_kwargs)
[rank1]:   File "/root/.conda/envs/llm/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
[rank1]:     return model_class.from_pretrained(
[rank1]:   File "/root/.conda/envs/llm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3620, in from_pretrained
[rank1]:     config = cls._autoset_attn_implementation(
[rank1]:   File "/root/.conda/envs/llm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1469, in _autoset_attn_implementation
[rank1]:     cls._check_and_enable_flash_attn_2(
[rank1]:   File "/root/.conda/envs/llm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1571, in _check_and_enable_flash_attn_2
[rank1]:     raise ImportError(f"{preface} the package flash_attn seems to be not installed. {install_message}")
[rank1]: ImportError: FlashAttention2 has been toggled on, but it cannot be used due to the following error: the package flash_attn seems to be not installed. Please refer to the documentation of https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2 to install Flash Attention 2.
W0608 23:20:40.091000 140396167001088 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 34011 closing signal SIGTERM
E0608 23:20:40.204000 140396167001088 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 34010) of binary: /root/.conda/envs/llm/bin/python
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-devel package with yum
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
[93m [WARNING] [0m sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
[93m [WARNING] [0m using untested triton version (2.3.1), only 1.0.0 is known to be compatible
Traceback (most recent call last):
  File "/root/.conda/envs/llm/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/.conda/envs/llm/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/root/.conda/envs/llm/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1082, in launch_command
    deepspeed_launcher(args)
  File "/root/.conda/envs/llm/lib/python3.10/site-packages/accelerate/commands/launch.py", line 786, in deepspeed_launcher
    distrib_run.run(args)
  File "/root/.conda/envs/llm/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/root/.conda/envs/llm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/.conda/envs/llm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-08_23:20:40
  host      : JF5300-B11A265T.jf.intel.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 34010)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
